networks:
  jenkins:
    driver: bridge

# TODO: Think about using a specific directory on the host for the volumes
volumes:
  jenkins-docker-certs:
  jenkins-data:

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    - 50000:50000
    environment:
    - DOCKER_HOST=tcp://docker:2376
    - DOCKER_CERT_PATH=/certs/client
    - DOCKER_TLS_VERIFY=1
    networks:
    - jenkins
    hostname: jenkins
    restart: always
    volumes:
    - jenkins-data:/var/jenkins_home
    - jenkins-docker-certs:/certs/client:ro
    depends_on:
    - dind
  dind:
    image: docker:dind
    ports:
    - 2376:2376
    - 5000:5000
    - 5001:5001
    environment:
    - DOCKER_TLS_CERTDIR=/certs
    networks:
    - jenkins
    privileged: true
    hostname: docker
    restart: always
    volumes:
    - jenkins-docker-certs:/certs/client
    - jenkins-data:/var/jenkins_home

